name: Build and Release

on: workflow_dispatch

jobs:
  build:
    name: Build and Release
    runs-on: macos-12

    steps:
      - name: Checkout CLI
        uses: actions/checkout@v2
        with:
          repository: teamlumos/hackathon-cli
          ref: main
          ssh-key: ${{ secrets.CLI_PRIVATE_KEY }}

      - run: ls -a
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6

      - name: Install Dependencies
        run: |
          pip install poetry
          brew install coreutils
      - name: Install Dependencies
        run: |
          poetry run pyinstaller --onefile lumos/__main__.py
          cd ./dist
          mv __main__ lumos
          release_file=$(pwd)/lumos
          echo $release_file
          sha=$(sha256sum $release_file | cut -d ' ' -f1)
          echo $sha
