name: Build and Release

on: workflow_dispatch

jobs:
  build:
    name: Build and Release
    runs-on: macos-12

    steps:
      - name: Checkout CLI
        uses: actions/checkout@v2
        with:
          repository: teamlumos/hackathon-cli
          ref: main
          ssh-key: ${{ secrets.CLI_PRIVATE_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6

      - name: Install Dependencies
        id: install-dependencies
        run: |
          pip install poetry
          brew install coreutils
          brew install gh
          brew install teamlumos/tap/lumos
          poetry install
          BREW_VERSION=$(lumos --version | awk '{print $3}')
          echo Current version on brew: $BREW_VERSION
          LUMOS_VERSION=$(poetry run python -m lumos --version | awk '{print $3}')
          echo New version: $LUMOS_VERSION
          echo "lumos-version=$LUMOS_VERSION" >> "$GITHUB_OUTPUT"
          echo "brew-version=$BREW_VERSION" >> "$GITHUB_OUTPUT"
  
      - name: Build
        id: build
        run: |
          poetry run pyinstaller --onefile lumos/__main__.py
          cd ./dist
          mv __main__ lumos
          tar -czf lumos.tar.gz *
          mv lumos.tar.gz ~
          RELEASE_FILE=~/lumos.tar.gz
          FILE_SHA=$(sha256sum $RELEASE_FILE | cut -d ' ' -f1)
          echo SHA: $FILE_SHA
          echo "release-file=$RELEASE_FILE" >> "$GITHUB_OUTPUT"
          echo "file-sha=$FILE_SHA" >> "$GITHUB_OUTPUT"

      - name: Checkout homebrew
        uses: actions/checkout@v2

      - run: pwd
      
      - name: Create tag & release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_FILE=${{ steps.build.outputs.release-file }}
          LUMOS_VERSION=${{ steps.install-dependencies.outputs.lumos-version }}
          echo "Creating tag & release $LUMOS_VERSION"
          git tag $LUMOS_VERSION
          git push --tags
          gh release create $LUMOS_VERSION --title "$LUMOS_VERSION" --notes "$LUMOS_VERSION" --latest "$RELEASE_FILE"
     
      - name: Update formula
        run: |
          LUMOS_VERSION=${{ steps.install-dependencies.outputs.lumos-version }}
          BREW_VERSION=${{ steps.install-dependencies.outputs.brew-version }}
          FILE_SHA=${{ steps.build.outputs.file-sha }}
          sed -i '' "s/$BREW_VERSION/$LUMOS_VERSION/" "./Formula/lumos.rb"
          sed -i '' "s/sha256 \".*\"/sha256 \"$FILE_SHA\"/" "./Formula/lumos.rb"
          msg="Update lumos from $BREW_VERSION to $LUMOS_VERSION"
          git commit -am "$msg"
          git push

