name: Build and Release

on: workflow_dispatch

jobs:
  build:
    name: Build and Release
    runs-on: macos-12

    steps:
      - name: Checkout CLI
        uses: actions/checkout@v2
        with:
          repository: teamlumos/hackathon-cli
          ref: main
          
      - run: ls -a
          
      - name: Checkout homebrew
        uses: actions/checkout@v2

      - run: ls -a

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6

      - name: Install Dependencies
        run: |
          cd hackathon-cli
          pip install poetry
          brew install coreutils
