name: Build and Release

on: workflow_dispatch

jobs:
  build:
    name: Build and Release
    runs-on: macos-12

    steps:
      - name: Checkout CLI
        uses: actions/checkout@v2
        with:
          repository: teamlumos/hackathon-cli
          ref: main
          ssh-key: ${{ secrets.CLI_PRIVATE_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6

      - name: Install Dependencies
        run: |
          pip install poetry
          brew install coreutils
          brew install gh
          brew install teamlumos/tap/lumos
          poetry install
          brew_version=$(lumos --version | awk '{print $3}')
          echo Current version: $brew_version
          lumos_version=$(poetry run python -m lumos --version | awk '{print $3}')
          echo New version: $lumos_version
  
      - name: Build
        run: |
          poetry run pyinstaller --onefile lumos/__main__.py
          cd ./dist
          mv __main__ lumos
          tar -czf lumos.tar.gz *
          mv lumos.tar.gz ~
          release_file=~/lumos.tar.gz
          sha=$(sha256sum $release_file | cut -d ' ' -f1)
          echo SHA: $sha

      - name: Checkout homebrew
        uses: actions/checkout@v2

      - run: pwd

      - name: Create tag
        id: create_tag
        run: |
          git tag $lumos_version
          git push origin $lumos_version
          
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create $lumos_version --title "$lumos_version" --notes "$$lumos_version" --latest "$release_file"

